#ifndef __DebugSudokuMainFrame__
#define __DebugSudokuMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "DSudoku.h"

//// end generated include

/** Implementing MainFrame */
class DebugSudokuMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void OnClose( wxCloseEvent& event );
		void OnChar( wxKeyEvent& event );
		void OnLeftUp( wxMouseEvent& event );
		void OnPaint( wxPaintEvent& event );
		void OnNumButtonClick( wxCommandEvent& event );
		void OnSetButtonClick( wxCommandEvent& event );
		void OnNoteButtonClick( wxCommandEvent& event );
		void OnClearButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		DebugSudokuMainFrame( wxWindow* parent );
	//// end generated class members
	
};

#endif // __DebugSudokuMainFrame__
